### ISSUE TITLE
Review the way sessions are handled

### ISSUE THREAD

**Issue by Wim-De-Clercq** [koenedaele/skosprovider_sqlalchemy#58]
Reasonably often (it's rare, but not super rare). You'll get 500 errors from calls to `https://id.erfgoed.net/thesauri/xxx/yyy` which many of our applications are using.

I asked for logs and this was what's in it:
```
  File ".../venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 98, in concept_scheme
    return self._get_concept_scheme()
  File ".../venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 286, in go
    parent_object.session.close()
  File ".../venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1194, in close
    self._close_impl(invalidate=False)
  File ".../venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1233, in _close_impl
    transaction.close(invalidate)
  File ".../venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 556, in close
    self.session.begin()
  File ".../venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 857, in begin
    "A transaction is already begun.  Use "
InvalidRequestError: A transaction is already begun.  Use subtransactions=True to allow subtransactions.
```

Difficult to pinpoint what exactly is wrong here.

I deployed thesaurus locally and added some logging to the `session_factory`  (See the print statements) 

_okay, prints may print in the wrong order, but it's not super important._
```py
def session_factory(session_maker_name):
    def with_session(fn):
        def go(parent_object, *args, **kw):
            if hasattr(parent_object, session_maker_name):
                root_call = True
                session_maker = getattr(parent_object, session_maker_name)
                if not hasattr(parent_object, 'session'):
                    parent_object.session = None
                if parent_object.session is None:
                    session = session_maker()
                    parent_object.session = session
                    print("start", parent_object.session)
                else:
                    print("nope ", parent_object.session)
                    root_call = False
                try:
                    parent_object.session.begin(subtransactions=True)
                    ret = fn(parent_object, *args, **kw)
                    parent_object.session.commit()
                    return ret
                except:
                    parent_object.session.rollback()
                    print("RAISE", parent_object.session)
                    raise
                finally:
                    if root_call:
                        print("stop ", parent_object.session)
                        parent_object.session.close()
                        parent_object.session = None
            else:
                raise Exception('session_maker %s not found' % session_maker_name)

        return go
    return with_session
```
When I run 1 python process in a `while True` loop spamming `http://localhost:6543/conceptschemes/ERFGOEDTYPES` (json) everythign works fine. All requests are firing quick, sessions opening and closing.
Short snippet of log:
```
('start', <sqlalchemy.orm.session.Session object at 0x7f766d619d50>)
('stop ', <sqlalchemy.orm.session.Session object at 0x7f766d619d50>)
('start', <sqlalchemy.orm.session.Session object at 0x7f766d609390>)
('stop ', <sqlalchemy.orm.session.Session object at 0x7f766d609390>)
('start', <sqlalchemy.orm.session.Session object at 0x7f766d835bd0>)
('stop ', <sqlalchemy.orm.session.Session object at 0x7f766d835bd0>)
```

Now, I open another terminal and start a 2nd python process with a 2nd `while True` and spam as well.
**Immediately** this will error and crash both scripts.
And the logs at the end are
```
('start', <sqlalchemy.orm.session.Session object at 0x7f766d6e7c50>)
('stop ', <sqlalchemy.orm.session.Session object at 0x7f766d6e7c50>)
('start', <sqlalchemy.orm.session.Session object at 0x7f766d5da150>)
('nope '(, <sqlalchemy.orm.session.Session object at 0x7f766d5da150>)
'stop ', <sqlalchemy.orm.session.Session object at 0x7f766d5da150>)
('RAISE', <sqlalchemy.orm.session.Session object at 0x7f766d5da150>)
```

As we can see, the 2nd request tries to re-use the same session the first one had opened (`nope`). Then the first request tries to `close()` that one, and either that fails, or the 2nd fails later, I'm not sure.

Either way, this is a disaster because 2 seperate requests are using the same database session. (behind the scenes, this SQLAlchemyProvider instance is the same. That's alright but it is part of why we see this behaviour. The code of `if parent_object.session is None` assumes you have a different SQLAlchemyProvider per request or something).

This needs to be digged out further, and another approach must be taken so we have less or no more 500 failures for simple thesaurus calls.

----

Sqlalchemy docs: https://docs.sqlalchemy.org/en/13/orm/contextual.html

> The Session object is entirely designed to be used in a non-concurrent fashion

**Comment by Wim-De-Clercq** [comment]
The while true script:
```py
import requests 

while True:
res = requests.get('http://localhost:6543/conceptschemes/ERFGOEDTYPES', headers={'Accept': 'application/json'})
res.raise_for_status()
print('ok')
```
Nothing special. Run in 2 terminals and crash.

**Comment by koenedaele** [comment]
The idea to fix this is in https://github.com/koenedaele/pyramid_skosprovider/pull/61. Basically, instantiate providers per request and not globally. This would also fix issues with the application not starting if an external provider is down (think it would still be trouble during a request that uses that provider).
